### ISSUE TITLE
Export the init scripts Error .'sv stop huginn-web-1' exited with a non-zero return value: warning: huginn-web-1: unable to open supervise/ok: file does not exist

### ISSUE THREAD

**Issue by ledoarea** [cantino/huginn#1352]
Hello
I am reading the installation.md
The step of **"Export the init scripts"** had some trouble
sudo bundle exec rake production:export
```
root@localhost:/home/huginn/huginn# sudo bundle exec rake production:export --trace
** Invoke production:export (first_time)
** Invoke production:check (first_time)
** Execute production:check
** Execute production:export
** Execute production:stop
Stopping huginn ...
rake aborted!
'sv stop huginn-web-1' exited with a non-zero return value: warning: huginn-web-1: unable to open supervise/ok: file does not exist
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `call'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:33:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/huginn/huginn/lib/tasks/production.rake:57:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
Tasks: TOP => production:export
root@localhost:/home/huginn/huginn#
```
thank you!

**Comment by dsander** [comment]
Hi @ledoarea,

I have never seen this error before, which Linux distribution and version are you using?

**Comment by ledoarea** [comment]
Debian 7.0 x86 minimal
Maybe like this issue https://github.com/cantino/huginn/issues/1085
But , Im not sure
I do:
`sv force-stop huginn-jobs-1`
But Im getting this:
```
warning: huginn-jobs-1: unable to open supervise/ok: file does not exist
root@localhost:/home/huginn/huginn#
```

**Comment by dsander** [comment]
I did not find anything helpful while googling either. Do you have a link to the iso image you used to install that specific Debian version? As far as i remember I tested the manual installation guide using one of the more recent Debian 7.x releases, but probably not 7.0

**Comment by ledoarea** [comment]
I can give you my vps account
can you help me?
If that's all right, Please give me your email address
and my live.cn mail is  v3mars
Thank you very much!

**Comment by ledoarea** [comment]
Sorry , The Debian version is 7.9
Debian GNU/Linux 7.9 (wheezy)

**Comment by dsander** [comment]
@ledoarea I send you a mail with my public ssh key. 

The installation worked for me on a digital ocean droplet with Debian 7.9 x64, the only problem I had happened during `bundle install`.
```
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
```
fixed the problem and Huginn is running now.

**Comment by alxcord** [comment]
I have an similar problem in freebsd 9,  the same step,  "Export the init scripts",  it was takint too long to run so I stoped it (ctrl c),  stoped receiving the error deleting (actially i moved to an tmp dir)  the directores above /etc/service,  not sure the correct path,  take a look first. there is two folders one of them was huginn-web-1. I couldn't generate this yet,  it's still freezing.  I will try again later.

**Comment by alxcord** [comment]
same problem running as root, no good information running with trace.

```
[huginn@huginn ~/projects/huginn]$ sudo bundle exec rake production:export --trace
** Invoke production:export (first_time)
** Invoke production:check (first_time)
** Execute production:check
** Execute production:export
** Execute production:stop
Stopping huginn ...
Exporting new services ...
```

**Comment by ledoarea** [comment]
I try to fixed the problem , do 
```
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
```
but the problem still exists

**Comment by dsander** [comment]
@ledoarea The problem seems to have been that `runit` was not started after you installed it. I have no idea why that happened in all my test installations on debian the `runsvdir` was started automatically.
I ran `/usr/sbin/runsvdir-start &` manually and then `sudo bundle exec rake production:export` worked. You can continue with the next step of the installation which would be setting up [logrotate](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#setup-logrotate).
Your server only has 256MB of RAM, which can become an issue. We [recommend](https://github.com/cantino/huginn/blob/master/doc/manual/requirements.md#memory) at least 512MB of RAM + the same amount of swap

@alxcord I have no experience with FreeBSD, could it be the same problem that runit did not start automatically? Maybe @knu can help.

**Comment by ledoarea** [comment]
@dsander Ok , Thank you very much !!!!!!!!!!! 
I will upgrade my server to 512MB RAM , thanks for you help!!!

**Comment by alxcord** [comment]
Thanks for your help but it still not working. I think I kidnaped dsander's topic, do you think I should create a new one?

So I tried to run `/usr/sbin/runsvdir-start &` but it not exists. When just running `runit`  it complais it must run as pid 0. 
I realized I should run `runsvdir /etc/service &` because this directory is created by bundle, no luck.
I waited about 10 minutes.

```
[huginn@huginn ~/projects/huginn]$ sudo runsvdir /etc/service &
[3] 52157
[huginn@huginn ~/projects/huginn]$ sudo bundle exec rake production:export --trace
** Invoke production:export (first_time)
** Invoke production:check (first_time)
** Execute production:check
** Execute production:export
** Execute production:stop
Stopping huginn ...
Exporting new services ...
^Crake aborted!
Interrupt:
/home/huginn/projects/huginn/lib/tasks/production.rake:69:in `sleep'
/home/huginn/projects/huginn/lib/tasks/production.rake:69:in `block (2 levels) in <top (required)>'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1/monitor.rb:211:in `mon_synchronize'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/bin/rake:23:in `load'
/home/huginn/projects/huginn/vendor/bundle/ruby/2.1/bin/rake:23:in `<main>'
Tasks: TOP => production:export
[2]   FInished              runsvdir /etc/service

[3]+  Stoped sudo runsvdir /etc/service
```

**Comment by dsander** [comment]
@ledoarea Glad I could help! Were you able to complete the installation without further issues?

@alxcord What happens when you run the commands of the rake task manually?
```
# export
sudo rm -rf /etc/service/huginn*
sudo foreman export runit -a huginn -l /home/huginn/huginn/log /etc/service
# start
sudo sv start huginn_web_1
sudo sv start huginn_jobs_1
```

**Comment by ledoarea** [comment]
@dsander Yes, It works, Now Im trying to do something with Huginn , Thanks a lot!!

**Comment by alxcord** [comment]
So I tried:
```
[foreman export] creating: huginn-web-1
[foreman export] creating: huginn-web-1/env
[foreman export] creating: huginn-web-1/log
[foreman export] writing: huginn-web-1/run
[foreman export] setting huginn-web-1/run to mode 493
[foreman export] writing: huginn-web-1/env/APP_SECRET_TOKEN
[foreman export] writing: huginn-web-1/env/DOMAIN
[foreman export] writing: huginn-web-1/env/PORT
[foreman export] writing: huginn-web-1/env/DATABASE_ADAPTER
[foreman export] writing: huginn-web-1/env/DATABASE_RECONNECT
...
[foreman export] writing: huginn-jobs-1/env/ENABLE_INSECURE_AGENTS
[foreman export] writing: huginn-jobs-1/env/ENABLE_SECOND_PRECISION_SCHEDULE
[foreman export] writing: huginn-jobs-1/env/SCHEDULER_FREQUENCY
[foreman export] writing: huginn-jobs-1/env/EVENT_EXPIRATION_CHECK
[foreman export] writing: huginn-jobs-1/env/TIMEZONE
[foreman export] writing: huginn-jobs-1/env/FAILED_JOBS_TO_KEEP
[foreman export] writing: huginn-jobs-1/env/DELAYED_JOB_MAX_RUNTIME
[foreman export] writing: huginn-jobs-1/env/DELAYED_JOB_SLEEP_DELAY
[foreman export] writing: huginn-jobs-1/log/run
[foreman export] setting huginn-jobs-1/log/run to mode 493
```

The service fail:
```
[huginn@huginn ~/projects/huginn]$ sudo sv start huginn_web_1
fail: huginn_web_1: unable to change to service directory: file does not exist

[huginn@huginn ~/projects/huginn]$ sudo sv start huginn_jobs_1
fail: huginn_jobs_1: unable to change to service directory: file does not exist
```
try specify full path

```
[huginn@huginn ~/projects/huginn]$ sudo sv start /etc/service/huginn_web_1
fail: /etc/service/huginn_web_1: unable to change to service directory: file does not exist
```

dir exists:
```
[huginn@huginn ~/projects/huginn]$ ls /etc/service/huginn-web-1/
env     log     run
```
followed [this guide](http://serverfault.com/questions/400158/runit-created-first-service-directory-sv-start-testrun-does-not-work), 

```
cd /
sudo ln -s /etc/service
 sudo sv start /etc/service/huginn_web_1
```

no way.

**Comment by dsander** [comment]
@alxcord Sorry, I am out of ideas, it looks like runit behaves differently on FreeBSD then it does on Linux.

**Comment by Warloxx** [comment]
I just managed to setup huginn on freeNAS (based on freebsd) and discovered, apart from other problems, the same problem as @alxcord.

splitting up this command
`sudo bundle exec rake production:export`
as suggested by @dsander, I could, just as alxcord, run
`sudo foreman export runit -a huginn -l /home/huginn/huginn/log /etc/service`
successfully

Now to the problem with the services.
The man page of runit states that services are expected in /var/service. That explains why they could not be found unless the full path was specified. Also, at least my install, created the services with dashes "-" not underlines "_" in their names.
I did

```
mkdir /var/service
ln -s /etc/service/huginn-web-1 /var/service/
ln -s /etc/service/huginn-jobs-1 /var/service/
```

now 
`sudo sv start huginn-jobs-1`
only complains about
> unable to open supervice/ok: file does not exist


It turns out that the runit service watcher `runsvdir` wasn't running at all. So as I executed
`/usr/local/etc/runit/2 &`
everything came to life.

After that I just setup nginx and it worked.

Unfortunately I could not figure out yet how to start it automatically. I created a `/usr/local/etc/rc.d/runit` file and placed the above command in it, but it does not work on restart. I just keep it this way for now since the server is not supposed to restart very often anyway, I just have to remember what to type in.

I hope this helps someone else struggling with this.

**Comment by interki** [comment]
@Warloxx do you still have this jail, having trouble - and your the only instance I can find of someone getting huginn to run under bsd.

**Comment by Warloxx** [comment]
I'm afraid not. I had some trouble with it after I got it initially running. Especially with starting it up in the first place. And it was not really stable. I now run a VM jail that's running debian und put huginn there.

**Comment by cashweaver** [comment]
I ran into a very similar problem (or at least very similar output) on my Ubuntu VPS:

```
$ sudo bundle exec rake production:force_stop
Force stopping huginn ...
rake aborted!
Errno::ENOENT: No such file or directory - sv
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:83:in ``'
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:83:in `run'
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:93:in `with_retries'
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:76:in `block in run_sv'
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:75:in `each'
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:75:in `run_sv'
/var/www/huginn.cashweaver.com/lib/tasks/production.rake:43:in `block (2 levels) in <top (required)>'
/var/www/huginn.cashweaver.com/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/cweaver/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/home/cweaver/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
Tasks: TOP => production:force_stop
(See full trace by running task with --trace)
```

Turns out I needed to run:

```sh
$ sudo apt-get install runit
```

**Comment by IAMEVANHE** [comment]
I was having the same problem. Try "rm /home/huginn/huginn" (because I don't have any problem with MySQL, Nginx and Ruby, which are needed by my other apps), and rebuild the "/home/huginn/huginn" folder. It works for me.
