### ISSUE TITLE
IMAPFolderAgent crashes with undefined method `addresses' for #<Mail::UnstructuredField:0x007feaf1cf2090> exception.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#745]
For reasons not fully clear, the IMAPFolderAgent crashes from time to time with an undefined method `addresses' for #<Mail::UnstructuredField:0x007feaf1cf2090> exception.  Here's a stack trace:
```
undefined method `addresses' for #<Mail::UnstructuredField:0x007feaf1cf2090>
/home/drwho/.rvm/gems/ruby-2.1.0/gems/mail-2.6.3/lib/mail/field.rb:189:in `method_missing'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:266:in `block (2 levels) in check'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:238:in `each'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:238:in `all?'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:238:in `block in check'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:384:in `block (3 levels) in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:383:in `each'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:383:in `block (2 levels) in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:336:in `each'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:336:in `block in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:442:in `open'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:325:in `each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:232:in `check'
/home/drwho/huginn/app/models/agent.rb:425:in `async_check'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:82:in `block in timeout'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `catch'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `timeout'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/home/drwho/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:150:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'
```

**Comment by cantino** [comment]
cc @knu

**Comment by cantino** [comment]
Is this still happening for you?

**Comment by virtadpt** [comment]
I haven't gotten that exact stack trace lately, but I did get this one two days ago:
```
Exception during check. undefined method `attr' for nil:NilClass: /home/drwho/huginn/app/models/agents/imap_folder_agent.rb:538:in `fetch'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:543:in `body_parts'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:234:in `block in check'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:384:in `block (3 levels) in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:383:in `each'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:383:in `block (2 levels) in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:336:in `each'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:336:in `block in each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:442:in `open'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:325:in `each_unread_mail'
/home/drwho/huginn/app/models/agents/imap_folder_agent.rb:232:in `check'
/home/drwho/huginn/app/models/agent.rb:437:in `async_check'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/performable_method.rb:30:in `perform'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `call'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/home/drwho/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/drwho/.rvm/gems/ruby-2.1.5/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
bin/threaded.rb:47:in `block (2 levels) in <top (required)>'
bin/threaded.rb:17:in `safely'
bin/threaded.rb:44:in `block in <top (required)>'
```
It's been so infrequent I'm not sure it's worth keeping this ticket open.

**Comment by cantino** [comment]
@knu, what does it mean if the `@client` fetch of `BODY.PEEK[]` returns nothing on the `BODY[]` attr?  Should we just ignore this and retry?

**Comment by knu** [comment]
Hmm, I'm not sure.  Probably the agent found a text file created in the folder which could not be parsed as a mail.

**Comment by knu** [comment]
Is this still an issue?

**Comment by virtadpt** [comment]
I don't know.  Let me upgrade Huginn to the latest commit and I'll get back to you.

**Comment by virtadpt** [comment]
Updated to commit 1e57f3a4572f041be01e0a533d24c417235ab752.  I'll keep an eye on it and let you know what I see.

**Comment by virtadpt** [comment]
I haven't seen this exception since then.

**Comment by cantino** [comment]
Great!

**Comment by Chaosspeeder** [comment]
Hi, I am new to hugging and have almost no experience in ruby. Unfortunately I have the same problem: 

`
Exception during check. undefined method `addresses' for #<Mail::UnstructuredField:0x00000003f4bed0>: /usr/local/rvm/gems/ruby-2.3.0/gems/mail-2.6.3/lib/mail/field.rb:189:in `method_missing'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:230:in `block (2 levels) in check'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:202:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:202:in `all?'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:202:in `block in check'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:348:in `block (3 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:347:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:347:in `block (2 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:300:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:300:in `block in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:406:in `open'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:289:in `each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:196:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
`

![bildschirmfoto 2016-01-29 um 08 47 16](https://cloud.githubusercontent.com/assets/7107433/12669980/f99cdc02-c664-11e5-9c2a-e01ab0953f49.png)

**Comment by knu** [comment]
@Chaosspeeder Oh, you have a condition on "cc", I presume?

**Comment by knu** [comment]
The commit above should fix the issue.

**Comment by Chaosspeeder** [comment]
Hi. This was fast. I will try your fix ASAP. But no, I didn't use a condition on "cc". Here is my configuration: 

```
{
  "expected_update_period_in_days": "1",
  "host": "imap.gmail.com",
  "ssl": true,
  "username": "xxxx",
  "password": "yyyy",
  "folders": [
    "INBOX"
  ],
  "conditions": {
    "from": "no-reply@strava.com"
  }
}
```

**Comment by knu** [comment]
The error would occur when you have from/to/cc in conditions and the agent receives a mail without the corresponding header, so I guessed it was Cc because every mail usually has From and To.  Is it the case that caused the problem has no From header?

**Comment by Chaosspeeder** [comment]
How can I figure it out that a mail has no From header? Thank you your help.

**Comment by Chaosspeeder** [comment]
Hi knu, unfortunately the error persists. I needed some time to update my configuration under Centos 6.5 (not officially supported). I will investigate the problem further in the next days.

```
Exception during check. undefined method `addresses' for #<Mail::UnstructuredField:0x007ff124272460>: /usr/local/rvm/gems/ruby-2.2.1/gems/mail-2.6.3/lib/mail/field.rb:189:in `method_missing'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:231:in `block (2 levels) in check'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:202:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:202:in `all?'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:202:in `block in check'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:349:in `block (3 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:348:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:348:in `block (2 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:301:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:301:in `block in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:407:in `open'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:290:in `each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:196:in `check'
```

**Comment by knu** [comment]
Looks like the From header of the problematic mail is broken and regarded as unstructured.  Please retry with the latest master!

**Comment by Chaosspeeder** [comment]
Great. no exception anymore. Good work. Thank you very much.

**Comment by knu** [comment]
Good to hear it is fixed!

I'm closing this since the original problem is fixed as well.
