### ISSUE TITLE
Not able to install docker image with docker-machine or Kitematic on OS X

### ISSUE THREAD

**Issue by andywenk** [cantino/huginn#981]
Hi,

first of all thanks for huginn. This looks awesome. Unfortunately, I can't get the docker image cantino/huginn working. I followed the instruction for both docker-machine and Kitematic at https://github.com/cantino/huginn/blob/master/doc/docker/install.md. Following you will see the log output from Kitematic after restarting the image:

    21 15:28:34,385 CRIT Set uid to user 0
    2015-08-21 15:28:34,385 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
    2015-08-21 15:28:34,386 WARN Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
    2015-08-21 15:28:34,386 WARN Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
    2015-08-21 15:28:34,443 INFO RPC interface 'supervisor' initialized
    2015-08-21 15:28:34,443 CRIT Server 'unix_http_server' running without any HTTP authentication checking
    2015-08-21 15:28:34,444 INFO supervisord started with pid 1
    2015-08-21 15:28:35,463 INFO spawned: 'stdout' with pid 21
    2015-08-21 15:28:35,465 INFO spawned: 'bootstrap' with pid 22
    2015-08-21 15:28:35,475 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
    2015-08-21 15:28:35,803 INFO spawned: 'mysqld' with pid 29
    2015-08-21 15:28:37,118 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    2015-08-21 15:28:37,120 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    bootstrap stdout | DATABASE_HOST=
    bootstrap stdout | mysqld: available
    bootstrap stdout | mysqld: added process group
    bootstrap stdout | Starting mysql server...
    mysqld stderr | 150821 15:28:36 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
    mysqld stdout | 150821 15:28:36 mysqld_safe Logging to '/var/log/mysql/error.log'.
    mysqld stdout | 150821 15:28:36 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
    bootstrap stdout | .2015-08-21 15:28:38,285 INFO spawned: 'foreman' with pid 411
    2015-08-21 15:28:38,287 INFO success: foreman entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
    2015-08-21 15:28:38,299 INFO exited: bootstrap (exit status 0; expected)
    foreman stderr | rake aborted!
    foreman stderr | NameError: uninitialized constant LetterOpenerWeb
    /app/config/routes.rb:80:in `block in <top (required)>'
    /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
    /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
    /app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:410:in `draw'
    /app/config/routes.rb:1:in `<top (required)>'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:40:in `each'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
    /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/file_update_checker.rb:75:in `call'
    /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/file_update_checker.rb:75:in `execute'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:27:in `updater'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `instance_exec'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `run'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/initializable.rb:54:in `run_initializers'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application.rb:352:in `initialize!'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `public_send'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `method_missing'
    /app/config/environment.rb:8:in `<top (required)>'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application.rb:328:in `require_environment!'
    /app/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/application.rb:457:in `block in run_tasks_blocks'
    Tasks: TOP => db:migrate => environment
    (See full trace by running task with --trace)
    2015-08-21 15:28:48,529 INFO exited: foreman (exit status 1; not expected)
    2015-08-21 15:29:01,804 WARN received SIGTERM indicating exit request

So there are warnings (errors) with MySQL and while running some rake tasks: 

    foreman stderr | rake aborted!
    foreman stderr | NameError: uninitialized constant LetterOpenerWeb

Any idea what is wrong? Which system info do you need? I am using Mac OS X 10.10.5 (14F27) and Virtualbox 5.0.2 r102096

Thanks a lot and all the best

Andy

**Comment by cantino** [comment]
@TildeWill added LetterOpenerWeb recently, so that's a bit worrying.

I don't see it running `bundle`.  Is the Docker image running in the production or development Rails env?

I may have to dig into this tomorrow unless @ianblenke, @TildeWill, or @dsander know what's going on.

**Comment by ianblenke** [comment]
This does seem like a dependency isn't being fulfilled:

```
bootstrap stdout | .2015-08-21 15:28:38,285 INFO spawned: 'foreman' with pid 411
2015-08-21 15:28:38,287 INFO success: foreman entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2015-08-21 15:28:38,299 INFO exited: bootstrap (exit status 0; expected)
foreman stderr | rake aborted!
foreman stderr | NameError: uninitialized constant LetterOpenerWeb
/app/config/routes.rb:80:in `block in <top (required)>'
```

I can't find mention of LetterOpenerWeb outside of this singular occurrence:

https://github.com/cantino/huginn/blob/master/config/routes.rb#L80

```
mount LetterOpenerWeb::Engine, at: "/letter_opener"
```

Looking at the git blame for that, it looks like PR #967 over a week ago may have introduced that.
There is indeed a `letter_opener_web` dependency in the `Gemfile`.

This suggests that bundler should have included it.

Looking at the Dockerfile, the CMD starts `/scripts/init`

https://github.com/cantino/huginn/blob/master/docker/Dockerfile#L31

```
CMD ["/scripts/init"]
```

The `/scripts/init` comes from the `docker/scripts/` directory in the project:

https://github.com/cantino/huginn/blob/master/docker/Dockerfile#L22-L23

```
ADD scripts/ /scripts
RUN chmod 755 /scripts/setup /scripts/init
```

So what is running is this script:

https://github.com/cantino/huginn/blob/master/docker/scripts/init

Which in turn creates a `supervisord` config and runs it:

https://github.com/cantino/huginn/blob/master/docker/scripts/init#L167-L183

Which first generates a script to start huginn:

https://github.com/cantino/huginn/blob/master/docker/scripts/init#L146-L163

```
#!/bin/bash -e
source /app/.env
# Assuming we have a created database, run the migrations and seed it idempotently.
[ -z "\${DO_NOT_MIGRATE}" ] && sudo -u huginn -EH bundle exec rake db:migrate
[ -z "\${DO_NOT_SEED}" ] && sudo -u huginn -EH bundle exec rake db:seed
[ -n "\$INTENTIONALLY_SLEEP" ] && sleep \$INTENTIONALLY_SLEEP
# Fixup the Procfile and prepare the PORT
[ -n "\${DO_NOT_RUN_JOBS}" ] && perl -pi -e 's/^jobs:/#jobs:/' /app/Procfile
perl -pi -e 's/rails server -b0.0.0.0\$/rails server -b 0.0.0.0 -p \\\$PORT/' /app/Procfile
export PORT="\${PORT:-3000}"
# Start huginn
exec sudo -u huginn -EH bundle exec foreman start
```

As you can see,  that script does indeed run `bundle exec foreman start` as the huginn user.

It then generates a foreman configuration to run that as a process:

```
cat > /etc/supervisor/conf.d/foreman.conf <<EOF
[program:foreman]
command=/tmp/foreman.sh
priority=10
directory=/app
process_name=%(program_name)s
autostart=false
autorestart=false
stdout_events_enabled=true
stderr_events_enabled=true
stopsignal=TERM
startsecs=0
stopwaitsecs=1
EOF

# start supervisord
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
```

It is easy to reproduce the problem:

```
$ docker run -ti --name huginn cantino/huginn
...
foreman stderr | rake aborted!
NameError: uninitialized constant LetterOpenerWeb
foreman stderr | /app/config/routes.rb:80:in `block in <top (required)>'
...
```

Now that we have an initialized container, let's try running the `/tmp/foreman.sh` script directly:

```
$ docker exec -ti huginn bash -li
root@87d02a6860e5:/# cd /app
root@87d02a6860e5:/app# bash -x /tmp/foreman.sh
```

That errors out the same way.

I tried adding a require, but it's not that it's not requiring something that is there... the bundle install simply isn't installing it.

I can fix this manually by doing a:

```
bundle install --with development
```

Now if I run `bash -x /tmp/foreman.sh` again, it works just fine.

So the problem here is that the `bundle install` isn't including the `development` group from the `Gemfile`.

That seems to be a problem here:

https://github.com/cantino/huginn/blob/master/docker/scripts/setup#L32

`
sudo -u huginn -H bundle install --deployment --without development test
`

So, to fix this, I've generated PR #982, which should address this problem.

**Comment by cantino** [comment]
What RAILS_ENV does Docker run in?

**Comment by dsander** [comment]
@andywenk The latest docker image should now work again. Do you mind checking it?

**Comment by andywenk** [comment]
@dsander Yay - thanks a lot. After 

    docker pull docker pull cantino/huginn

in docker-machine and 

    docker run -it -p 3000:3000 cantino/huginn

the conatiner started and I was able to login ti huginn.

Short hint. I still get this MySQL warning:

    bootstrap stdout | Starting mysql server...
    mysqld stderr | 150823 12:25:00 mysqld_safe Can't log to error log and syslog at the same time.     
       Remove all --log-error configuration options for --syslog to take effect.
    mysqld stdout | 150823 12:25:00 mysqld_safe Logging to '/var/log/mysql/error.log'.
    mysqld stdout | 150823 12:25:00 mysqld_safe Starting mysqld daemon with databases from  
      /var/lib/mysql

Thanks again and all the best

Andy
